test1:
	go test -test.run ^Test3_5_1_1$

test2:
	go test -test.run ^Test3_5_1_2$

test3:
	go test -test.run ^Test3_5_2$

test4:
	go test -test.run ^Test3_5_3$

test5:
	go test -test.run ^Test3_5_4_1$

test6:
	go test -test.run ^Test3_5_4_2$

test7:
	go test -test.run ^Test3_5_4_3$

test8:
	go test -test.run ^Test3_5_4_4$

test9:
	go test -test.run ^Test3_5_4_5$