test1:
	go test -test.run ^Test3_5_1_1$

test2:
	go test -test.run ^Test3_5_1_2$

test3:
	go test -test.run ^Test3_5_2$

test4:
	go test -test.run ^Test3_5_3$

test5:
	go test -test.run ^Test3_5_4_1$

test6:
	go test -test.run ^Test3_5_4_2$

test7:
	go test -test.run ^Test3_5_4_3$

test8:
	go test -test.run ^Test3_5_4_4$

test9:
	go test -test.run ^Test3_5_4_5$

test10:
	go test -test.run ^Test3_5_4_1_1$

test11:
	go test -test.run ^Test3_5_4_1_2$

test12:
	go test -test.run ^Test3_5_4_1_3$

test13:
	go test -test.run ^Test3_5_4_2_1$

test14:
	go test -test.run ^Test3_5_4_2_2$

test15:
	go test -test.run ^Test3_5_4_2_3$

test16:
	go test -test.run ^Test3_5_4_3_1$

test17:
	go test -test.run ^Test3_5_4_3_2$

test18:
	go test -test.run ^Test3_5_4_3_3$

test19:
	go test -test.run ^Test3_5_4_4_1$

test20:
	go test -test.run ^Test3_5_4_4_2$