test1:
	go test -test.run ^Test3_5_1_1$

test2:
	go test -test.run ^Test3_5_1_2$

test3:
	go test -test.run ^Test3_5_2$

test4:
	go test -test.run ^Test3_5_3$

test5:
	go test -test.run ^Test3_5_4_1$

test6:
	go test -test.run ^Test3_5_4_2$

test7:
	go test -test.run ^Test3_5_4_3$

test8:
	go test -test.run ^Test3_5_4_4$

test9:
	go test -test.run ^Test3_5_4_5$

test10:
	go test -test.run ^Test3_5_4_1_1$

test11:
	go test -test.run ^Test3_5_4_1_2$

test12:
	go test -test.run ^Test3_5_4_1_3$

test13:
	go test -test.run ^Test3_5_4_2_1$

test14:
	go test -test.run ^Test3_5_4_2_2$

test15:
	go test -test.run ^Test3_5_4_2_3$

test16:
	go test -test.run ^Test3_5_4_3_1$

test17:
	go test -test.run ^Test3_5_4_3_2$

test18:
	go test -test.run ^Test3_5_4_3_3$

test19:
	go test -test.run ^Test3_5_4_4_1$

test20:
	go test -test.run ^Test3_5_4_4_2$

test21:
	go test -test.run ^Test3_5_4_5_1$

test22:
	go test -test.run ^Test3_5_4_5_2$

test23:
	go test -test.run ^Test3_5_4_5_3$

test24:
	go test -test.run ^Test3_5_4_6_1$

test25:
	go test -test.run ^Test3_5_5_1$

test26:
	go test -test.run ^Test3_5_5_2$

test27:
	go test -test.run ^Test3_5_6_1$

test28:
	go test -test.run ^Test3_5_6_2$

test29:
	go test -test.run ^Test3_5_7_1$

test30:
	go test -test.run ^Test3_5_7_2$

test31:
	go test -test.run ^Test3_5_7_3$

test32:
	go test -test.run ^Test3_5_8_1$

test33:
	go test -test.run ^Test3_5_8_2$

test34:
	go test -test.run ^Test3_5_8_3$

test35:
	go test -test.run ^Test3_5_9_1$

test36:
	go test -test.run ^Test3_5_9_2$

test37:
	go test -test.run ^Test3_5_10_1$

test38:
	go test -test.run ^Test3_5_10_2$