packagemgt

import(
	"lab.siroccotechnology.ru/tp/common/messages/carriers"
	"lab.siroccotechnology.ru/tp/common/messages/processing"
	"lab.siroccotechnology.ru/tp/integration-testing/test"
)

varCasesMGT1=test.Cases{
	{
		N:"26.MGT-MMTS-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"27.MGT-MMTS-MGT-MM-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"28.MGT-MMTS-MGT-MM-MGT-MCK-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"29.MGT-MMTS-MGT-MM-MGT-MCK-MGT-MM-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"30.MGT-MMTS-MGT-MCK-MGT-MM-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"31.MGT-MCD1_MO-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2002910",//НЕМЧИНОВКА
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",//ОДИНЦОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"32.MGT-MCD2_MO-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000460",//НАХАБИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2003960",//ПАВШИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"33.MGT-MCD1_MSK-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000700",//ТЕСТОВСКАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000455",//ДЕГУНИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"34.MGT-MCD2_MSK-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"35.MGT-MCD1_MO-MSK-MGT-MM-MGT-MCD1_MSK-MO-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",//ОДИНЦОВО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000455",//ДЕГУНИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000700",//ТЕСТОВСКАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",//ОДИНЦОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"36.MGT-MCD2_MO-MSK-MGT-MM-MGT-MCD2_MSK-MO-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000460",//НАХАБИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000037",//БИТЦА
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"37.MGT-MCD1_MO-MSK-MGT-MCK-MGT-MCD1_MSK-MO-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2002910",//НЕМЧИНОВКА
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",//СЕТУНЬ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2002077",//МАРК
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000600",//НОВОДАЧНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"38.MGT-MCD2_MO-MSK-MGT-MCK-MGT-MCD2_MSK-MO-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000460",//НАХАБИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000630",//БУТОВО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"39.MGT-MCD1_MO-MSK-MGT-MM-MGT-MCK-MGT-MM-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",//ОДИНЦОВО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000455",//ДЕГУНИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"40.MGT-MCD2_MO-MSK-MGT-MM-MGT-MCK-MGT-MM-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000460",//НАХАБИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000235",//ДМИТРОВСКАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"41.MGT-MCD1_MO-MSK-MGT-MMTS-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000600",//НОВОДАЧНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2002077",//МАРК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"42.MGT-MCD2_MO-MSK-MGT-MMTS-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000720",//ОПАЛИХА
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001410",//ГРАЖДАНСКАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"43.MGT-MCD1_MO-MSK-MGT-MM-MGT-MMTS-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",//ОДИНЦОВО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000455",//ДЕГУНИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},

	{
		N:"44.MGT-MCD2_MO-MSK-MGT-MM-MGT-MMTS-MGT",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000720",//ОПАЛИХА
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2002780",//ДЕПО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MGT,
				ExpectedSum:4200,
			},
		},
	},
}
