packagemcd

import(
	"lab.siroccotechnology.ru/tp/common/messages/carriers"
	"lab.siroccotechnology.ru/tp/common/messages/processing"
	"lab.siroccotechnology.ru/tp/integration-testing/test"
)

varCasesComplexMCDMOPartThree=test.Cases{
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММ-МMTS",//30
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММ-МЦДМСК1",//31
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММ-МЦДМО1",//32
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-МЦК-ММ",//33
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-МЦК-МЦК",//34
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-МЦК-ММТС",//35
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-МЦК-МЦДМСК1",//36
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-МЦК-МЦДМСК/МО1",//37
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//ЛОБНЯ2000009
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//САВЕЛОВСКИЙВОКЗАЛ2000115
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММТС-ММ",//38
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММТС-МЦК",//39
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММТС-ММТС",//40
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-ММТС-МЦДМСК1",//41
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-ММТС-МЦДМСК/МО1",//42
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//ЛОБНЯ2000009
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//САВЕЛОВСКИЙВОКЗАЛ2000115
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-ММ",//43
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-МЦК",//44
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-ММТС",//45
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-МЦД_МСК_1",//46
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			//&Pass{
			//	PaymentType:PaymentTypePayment,
			//	Carrier:carriers.Carrier_MCD,
			//	SubCarrier:carriers.SubCarrier_MCD1_MSK,
			//	Terminal:&processing.Terminal{
			//		Station:"2000155",//ФИЛИ
			//		Direction:processing.TerminalDirection_INGRESS,
			//	},
			//	ExpectedSum:4200,
			//},
			//&Pass{
			//	PaymentType:PaymentTypeFree,
			//	Carrier:carriers.Carrier_MCD,
			//	SubCarrier:carriers.SubCarrier_MCD1_MSK,
			//	Terminal:&processing.Terminal{
			//		Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
			//		Direction:processing.TerminalDirection_EGRESS,
			//	},
			//	Ingress:6,
			//},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦДМСК2-МЦД_МСК/МО_1",//47
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ2000009
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ2000115
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	//{
	//	N:"МЦДМО/МСК1-ММ-МЦДМСК2-МЦД_МСК/МО_1",//47
	//	T:T{
	//		&Pass{
	//			PaymentType:PaymentTypePayment,
	//			Carrier:carriers.Carrier_MCD,
	//			SubCarrier:carriers.SubCarrier_MCD1_MO,
	//			Terminal:&processing.Terminal{
	//				Station:"2000115",//ЛОБНЯ
	//				Direction:processing.TerminalDirection_INGRESS,
	//			},
	//			ExpectedSum:4900,
	//		},
	//		&Pass{
	//			PaymentType:PaymentTypeFree,
	//			Carrier:carriers.Carrier_MCD,
	//			SubCarrier:carriers.SubCarrier_MCD1_MSK,
	//			Terminal:&processing.Terminal{
	//				Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
	//				Direction:processing.TerminalDirection_EGRESS,
	//			},
	//			Ingress:1,
	//		},
	//		&Pass{
	//			PaymentType:PaymentTypeFree,
	//			Carrier:carriers.Carrier_MM,
	//			SubCarrier:carriers.SubCarrier_MM_SUB,
	//			Parent:1,
	//		},
	//		&Pass{
	//			PaymentType:PaymentTypeFree,
	//			Carrier:carriers.Carrier_MCD,
	//			SubCarrier:carriers.SubCarrier_MCD2_MSK,
	//			Terminal:&processing.Terminal{
	//				Station:"2000075",//ТУШИНО
	//				Direction:processing.TerminalDirection_INGRESS,
	//			},
	//			Parent:1,
	//		},
	//		&Pass{
	//			PaymentType:PaymentTypeFree,
	//			Carrier:carriers.Carrier_MCD,
	//			SubCarrier:carriers.SubCarrier_MCD2_MSK,
	//			Terminal:&processing.Terminal{
	//				Station:"2000200",//КАЛИТНИКИ
	//				Direction:processing.TerminalDirection_EGRESS,
	//			},
	//			Ingress:4,
	//		},
	//		&Pass{
	//			PaymentType:PaymentTypePayment,
	//			Carrier:carriers.Carrier_MCD,
	//			SubCarrier:carriers.SubCarrier_MCD1_MSK,
	//			Terminal:&processing.Terminal{
	//				Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ2000009
	//				Direction:processing.TerminalDirection_INGRESS,
	//			},
	//			ExpectedSum:4200,
	//		},
	//		&Pass{
	//			PaymentType:PaymentTypePayment,
	//			Carrier:carriers.Carrier_MCD,
	//			SubCarrier:carriers.SubCarrier_MCD1_MO,
	//			Terminal:&processing.Terminal{
	//				Station:"2000115",//ЛОБНЯ2000115
	//				Direction:processing.TerminalDirection_EGRESS,
	//			},
	//			Ingress:6,
	//			ExpectedSum:700,
	//		},
	//	},
	//},
	{
		N:"МЦДМО/МСК1-ММ-МЦД_МСК/МО_2-ММ",//48
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ2001840
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ2002952
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦД_МСК/МО_2-МЦК",//49
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ2001840
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ2002952
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦД_МСК/МО_2-ММТС",//50
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ2001840
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ2002952
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦД_МСК/МО_2-МЦДМСК1",//51
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ2001840
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ2002952
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",//СЕТУНЬ2000275
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦД_МСК/МО_2-МЦДМСК/МО1",//52
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ2001840
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ2002952
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ2000009
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-МЦК-ММ-ММ",//53
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-МЦК-ММ-МЦК",//54
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-МЦК-ММ-ММТС-ММ",//55
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-МЦК-ММ-ММТС-МЦК",//56
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-МЦК-ММ-ММТС-ММТС",//57
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-МЦК-ММ-ММТС-МЦДМСК1",//58
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",//СЕТУНЬ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"МЦД_МО/МСК_1-МЦК-ММ-ММТС-МЦД_МСК/МО_1",//59
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",//СЕТУНЬ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"МЦД_МО/МСК_1-МЦК-ММ-МЦД_МСК_2-ММ",//60
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦД_МО/МСК_1-МЦК-ММ-МЦД_МСК_2-МЦК",//61
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦД_МО/МСК_1-МЦК-ММ-МЦД_МСК_2-ММТС",//62
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
}
