packagemcd

import(
	"lab.siroccotechnology.ru/tp/common/messages/carriers"
	"lab.siroccotechnology.ru/tp/common/messages/processing"
	"lab.siroccotechnology.ru/tp/integration-testing/test"
)

varCasesComplexMCDMOPartTwo=test.Cases{
	{
		N:"МЦД_МО/МСК_1-ММ-МЦК-ММ-МЦД_МО/МСК_1",//05
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"МЦДМО-ММ-МЦК-МЦК",//06
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО-ММ-МЦК-МMTS",//07
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
		},
	},
	{
		N:"МЦДМО-ММ-МЦК-МMTS-MM",//08
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО-ММ-МЦК-МMTS-MCK",//09
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО-ММ-МЦК-МMTS-MMTS",//10
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦК-МMTS-MЦДМСК1",//11
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2002077",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦК-МMTS-MЦДМО1",//12
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦК-МЦДМСК2-ММ",//13
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2002780",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦК-МЦДМСК2-МЦК",//14
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2002780",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦК-МЦДМСК2-МMTS",//15
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",//ОДИНЦОВО
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",//ТРИКОТАЖНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2002780",//ДЕПО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦК-МЦДМСК2-МЦДМСК1",//16
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000055",
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001840",
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2002780",
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000455",//ДЕГУНИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦК-МЦДМСК/МСК2-МЦДМСК/МО1",//17
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000225",//ЦАРИЦЫНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				ExpectedSum:700,
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦК-МЦДМСК/МО2-ММ",//18
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦК-МЦДМСК/МО2-МЦК",//19
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦК-МЦДМСК/МО2-ММТС",//20
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},

			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦК-МЦДМСК/МO2-МЦДМЦК1",//21
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",//СЕТУНЬ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000455",//ДЕГУНИНО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"МЦДМО/МСК1-ММ-МЦК-МЦДМСК/МO2-МЦДМСК/МО1",//22
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000001",//КУРСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2000065",//ПОДОЛЬСК
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000275",//СЕТУНЬ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-ММТС-ММ",//23
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-ММТС-МЦК",//24
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-ММТС-ММТС",//25
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-ММТС-МЦДМЦК1",//26
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-ММТС-МЦДМО1",//27
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММ-ММ",//28
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"МЦДМО1-ММ-МЦДМСК2-ММ-МЦК",//29
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4900,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000009",//САВЕЛОВСКИЙВОКЗАЛ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000075",//ТУШИНО
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000200",//КАЛИТНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:4,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
}
