packagemcd

import(
	"lab.siroccotechnology.ru/tp/common/messages/carriers"
	"lab.siroccotechnology.ru/tp/common/messages/processing"
	"lab.siroccotechnology.ru/tp/integration-testing/test"
)

varCasesMetroComplexMCDMSK5=test.Cases{
	{
		N:"101.МСК-МСК-МСК-МСК2-ММ-МЦК-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2001101",//ИННОВАЦИОННЫЙЦЕНТР
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"102.МСК-МСК-МСК-МСК2-ММ-ММТС-ММ",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"103.МСК-МСК-МСК-МСК2-ММ-ММТС-МЦК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"104.МСК-МСК-МСК-МСК2-ММ-ММТС-ММТС",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"105.МСК-МСК-МСК-МСК2-ММ-ММТС-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"106.МСК-МСК-МСК-МСК2-ММ-ММТС-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2001101",//ИННОВАЦИОННЫЙЦЕНТР
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"107.МСК-МСК-МСК-МСК2-ММ-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2003965",//ТИМИРЯЗЕВСКАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"108.МСК-МСК-МСК-МСК2-ММ-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2001340",//ВОДНИКИ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"109.МСК-МСК-МСК-МСК2-МЦК-ММ-ММ",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"110.МСК-МСК-МСК-МСК2-МЦК-ММ-МЦК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"111.МСК-МСК-МСК-МСК2-МЦК-ММ-ММТС",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"112.МСК-МСК-МСК-МСК2-МЦК-ММ-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"113.МСК-МСК-МСК-МСК2-МЦК-ММ-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000600",//НОВОДАЧНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"114.МСК-МСК-МСК-МСК2-МЦК-МЦК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"115.МСК-МСК-МСК-МСК2-МЦК-ММТС-ММ",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"116.МСК-МСК-МСК-МСК2-МЦК-ММТС-МЦК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"117.МСК-МСК-МСК-МСК2-МЦК-ММТС-ММТС",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"118.МСК-МСК-МСК-МСК2-МЦК-ММТС-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
			},
		},
	},
	{
		N:"119.МСК-МСК-МСК-МСК2-МЦК-ММТС-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000620",//ХЛЕБНИКОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:7,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"120.МСК-МСК-МСК-МСК2-МЦК-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"121.МСК-МСК-МСК-МСК2-МЦК-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000115",//ЛОБНЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"122.МСК-МСК-МСК-МСК2-ММТС-ММ",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"123.МСК-МСК-МСК-МСК2-ММТС-МЦК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"124.МСК-МСК-МСК-МСК2-ММТС-ММТС",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"125.МСК-МСК-МСК-МСК2-ММТС-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
			},
		},
	},
	{
		N:"126.МСК-МСК-МСК-МСК2-ММТС-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000100",//НОВОПРУДНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:6,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"127.МСК-МСК-МСК-МСК2-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
		},
	},
	{
		N:"128.МСК-МСК-МСК-МСК2-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2000595",//ПОКРОВСКОЕ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000100",//ДОЛГОПРУДНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
				ExpectedSum:700,
			},
		},
	},
	{
		N:"129.МСК-МСК-МСК-МО2-ММ",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
	{
		N:"130.МСК-МСК-МСК-МО2-МЦК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},
	{
		N:"131.МСК-МСК-МСК-МО2-ММТС",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},
	{
		N:"132.МСК-МСК-МСК-МО2-МСК-МСК",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
			},
		},
	},
	{
		N:"133.МСК-МСК-МСК-МО2-МСК-МО",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000185",//ЛИАНОЗОВО
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MSK,
				Terminal:&processing.Terminal{
					Station:"2001250",//МОСКВАТОВАРНАЯ
					Direction:processing.TerminalDirection_INGRESS,
				},
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD2_MO,
				Terminal:&processing.Terminal{
					Station:"2002952",//СИЛИКАТНАЯ
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:3,
				ExpectedSum:700,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MSK,
				Terminal:&processing.Terminal{
					Station:"2000155",//ФИЛИ
					Direction:processing.TerminalDirection_INGRESS,
				},
				ExpectedSum:4200,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				Carrier:carriers.Carrier_MCD,
				SubCarrier:carriers.SubCarrier_MCD1_MO,
				Terminal:&processing.Terminal{
					Station:"2000685",//БАКОВКА
					Direction:processing.TerminalDirection_EGRESS,
				},
				Ingress:5,
				ExpectedSum:700,
			},
		},
	},
}
