packagemmts

import(
	"lab.siroccotechnology.ru/tp/common/messages/carriers"
	"lab.siroccotechnology.ru/tp/integration-testing/test"
)

varCasesOfflineMetroComplexMMTS=test.Cases{

	{
		N:"1.MMTS-MMTS",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},

	{
		N:"2.MMTS-MM-MM",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},

	{
		N:"3.MMTS-MCK-MCK",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},

	{
		N:"4.MMTS-MM-MMTS",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},

	{
		N:"5.MMTS-MM-MCK-MCK",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},

	{
		N:"6.MMTS-MM-MCK-MM",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},

	{
		N:"7.MMTS-MCK-MM-MM",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},

	{
		N:"8.MMTS-MCK-MM-MCK",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},

	{
		N:"9.MMTS-MCK-MM-MMTS",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},

	{
		N:"10.MMTS-MM-MM-MM-MM",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},

	{
		N:"11.MMTS-MM-MCK-MM-MCK",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
			},
		},
	},

	{
		N:"12.MMTS-MM-MCK-MM-MMTS",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:1,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
		},
	},

	////MMTS-MMTS(notmoney)-MCK(еслибылодвеодинаковыепоездкиипоследняяизнихнеоплачена,комплекснаяпоездкадолжнасоздаватьсяипривязыватьсякпоследней)
	{
		N:"13.MMTS-MMTS-MCK",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,

				AuthType:test.AuthTypeIncorrect,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
		},
	},

	////Кейсывключающиетранзакцииснекорректнойавторизацией
	////"MMTS-MMTS(AuthTypeIncorrect)-MM-MCK-MM"(Еслибылодвеодинаковыепоездкиипоследняяизнихнеоплачена,комплекснаяпоездкадолжнасоздаватьсяипривязыватьсякпоследней)
	{
		N:"14.MMTS-MMTS-MM-MCK-MM",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,

				AuthType:test.AuthTypeIncorrect,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
		},
	},

	////"MMTS-MMTS(AuthTypeIncorrect)-MM-MCK-MM"(Еслибылодвеодинаковыепоездкиипоследняяизнихнеоплачена,комплекснаяпоездкадолжнасоздаватьсяипривязыватьсякпоследней)
	{
		N:"15.MMTS-MMTS-MM-MCK-MM",
		T:test.T{
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MMTS_SUB,

				AuthType:test.AuthTypeIncorrect,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MCK_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypeFree,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
				Parent:2,
			},
			&test.Pass{
				PaymentType:test.PaymentTypePayment,
				RequestType:test.RequestTypeOffline,
				Carrier:carriers.Carrier_MM,
				SubCarrier:carriers.SubCarrier_MM_SUB,
			},
		},
	},
}
