#!/usr/bin/env bash

./apm-api-gateway.run & ./auth-service.run & ./calculator-service.run & ./mk-emulator.run & ./pass-service.run & ./processing-api-gateway.run & ./request-service.run & ./tidpool-service.run & ./user-service.run & ./web-api-gateway.run && fg

 & ./pass-service-mcd.run & ./pass-service-mgt.run & ./pass-service-mtppk.run