processing_api:
  local: http://localhost:9090
  test: http://processing-api-gateway.test.svc.cluster.local:9090
  stage: http://processing-api-gateway.stage.svc.cluster.local:9090
  prod: http://processing-api-gateway.production.svc.cluster.local:9090

pass:
  local: http://localhost:13380
  test: http://pass-service.test.svc.cluster.local:13380
  stage: http://pass-service.stage.svc.cluster.local:13380
  prod: http://pass-service.production.svc.cluster.local:13380

apm_api:
  local: http://localhost:1340
  test: http://apm-api-gateway-public.test.svc.cluster.local:1340
  stage: http://apm-api-gateway-public.stage.svc.cluster.local:1340
  prod: ttp://apm-api-gateway-public.production.svc.cluster.local:1340